# Generated by Django 3.2.7 on 2022-06-30 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evac_Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50, verbose_name='Building Name')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('building_img', models.ImageField(default='default.jpg', upload_to='evac_center_imgs', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Evacuation Center',
                'verbose_name_plural': 'Evacuation Centers',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(choices=[('Alegria', 'Alegria'), ('Bagacay', 'Bagacay'), ('Baluntay', 'Baluntay'), ('Datal Anggas', 'Datal Anggas'), ('Domolok', 'Domolok'), ('Kawas', 'Kawas'), ('Ladol', 'Ladol'), ('Maribulan', 'Maribulan'), ('Pag-Asa', 'Pag-Asa'), ('Paraiso', 'Paraiso'), ('Poblacion', 'Poblacion'), ('Spring', 'Spring'), ('Tokawal', 'Tokawal')], default='Alegria', max_length=100, verbose_name='Barangay Name')),
                ('barangay_img', models.ImageField(blank=True, upload_to='history_imgs', verbose_name='Image')),
                ('barangay_info', models.TextField(verbose_name="Barangay's History")),
            ],
            options={
                'ordering': ['barangay_name'],
            },
        ),
        migrations.CreateModel(
            name='Warning_Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, verbose_name='Device Name')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('device_info', models.TextField(verbose_name='Description')),
                ('device_img', models.ImageField(default='default.jpg', upload_to='device_imgs', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Early Warning Device',
                'verbose_name_plural': 'Early Warning Devices',
            },
        ),
        migrations.CreateModel(
            name='Warning_Signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=50, verbose_name='Sign Name')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sign_img', models.ImageField(default='default.jpg', upload_to='sign_imgs', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Warning Sign',
                'verbose_name_plural': 'Warning Signs',
            },
        ),
        migrations.CreateModel(
            name='GeoHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geohazard_img', models.ImageField(blank=True, upload_to='history_imgs', verbose_name='Image')),
                ('geohazard_info', models.TextField(verbose_name='GeoHazard Description')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geohazards', to='auxiliary.history')),
            ],
            options={
                'verbose_name': 'GeoHazard',
                'verbose_name_plural': 'GeoHazards',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purok_name', models.CharField(max_length=50, verbose_name='Purok Name')),
                ('purok_coordinates', models.CharField(default='Not Specified', max_length=100, verbose_name='Coordinates')),
                ('flood_rating', models.CharField(choices=[('HIGH', 'HIGH'), ('HIGH (Mitigated)', 'HIGH (Mitigated)'), ('MODERATE', 'MODERATE'), ('MODERATE (Mitigated)', 'MODERATE (Mitigated)'), ('LOW', 'LOW'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=100, verbose_name='Flood Rating')),
                ('landslide_rating', models.CharField(choices=[('HIGH', 'HIGH'), ('HIGH (Mitigated)', 'HIGH (Mitigated)'), ('MODERATE', 'MODERATE'), ('MODERATE (Mitigated)', 'MODERATE (Mitigated)'), ('LOW', 'LOW'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=100, verbose_name='Landslide Rating')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='auxiliary.history')),
            ],
            options={
                'verbose_name': 'GeoHazard',
                'verbose_name_plural': 'GeoHazards',
            },
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announ_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
            ],
            options={
                'verbose_name_plural': 'Announcements',
                'ordering': ['-date_posted'],
            },
        ),
    ]
