# Generated by Django 3.2.7 on 2022-07-01 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auxiliary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['barangay_name'], 'verbose_name': 'History', 'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterModelOptions(
            name='warning_devices',
            options={'verbose_name': 'Warning Device', 'verbose_name_plural': 'Warning Devices'},
        ),
        migrations.AddField(
            model_name='history',
            name='date_published',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='evac_centers',
            name='building_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Building Name'),
        ),
        migrations.AlterField(
            model_name='geohazard',
            name='geohazard_info',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='history',
            name='barangay_info',
            field=models.TextField(verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='warning_devices',
            name='device_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Device Name'),
        ),
        migrations.AlterField(
            model_name='warning_signs',
            name='sign_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sign Name'),
        ),
        migrations.AlterUniqueTogether(
            name='announcements',
            unique_together={('title', 'content')},
        ),
    ]
