# Generated by Django 3.2.7 on 2022-07-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0002_auto_20220701_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date_published',
        ),
        migrations.AddField(
            model_name='geohazard',
            name='date_published',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
