# Generated by Django 3.2.7 on 2022-07-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0003_auto_20220701_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='purok_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Purok Name'),
        ),
    ]
