# Generated by Django 3.2.7 on 2022-07-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_alter_assessment_purok_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='purok_name',
            field=models.CharField(max_length=50, verbose_name='Purok Name'),
        ),
    ]
