# Generated by Django 3.2.7 on 2022-07-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0005_alter_assessment_purok_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='barangay_info',
            field=models.TextField(blank=True, verbose_name='History'),
        ),
    ]
