# Generated by Django 3.2.7 on 2022-07-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0006_alter_history_barangay_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geohazard',
            name='geohazard_img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='history_imgs', verbose_name='Image'),
        ),
    ]
