# Generated by Django 3.2.7 on 2022-07-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0007_alter_geohazard_geohazard_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='flood_rating',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH'), ('MODERATE (Mitigated)', 'MODERATE (Mitigated)'), ('HIGH (Mitigated)', 'HIGH (Mitigated)'), ('LOW-MODERATE', 'LOW-MODERATE'), ('MODERATE-HIGH', 'MODERATE-HIGH'), ('LOW(High Near Rivers)', 'LOW(High Near Rivers)'), ('LOW(H/M Near Rivers)', 'LOW(H/M Near Rivers)'), ('MODERATE(High Near Rivers)', 'MODERATE(High Near Rivers)'), ('LOW(High On Slopes)', 'LOW(High On Slopes)'), ('MODERATE(High On Slopes)', 'MODERATE(High On Slopes)'), ('LOW(H/M On Slopes)', 'LOW(H/M On Slopes)'), ('LOW(High Near Creeks)', 'LOW(High Near Creeks)'), ('LOW(Moderate Near Creeks)', 'LOW(Moderate Near Creeks)'), ('MODERATE(High Near Creeks)', 'MODERATE(High Near Creeks)'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=100, verbose_name='Flood Rating'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='landslide_rating',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH'), ('MODERATE (Mitigated)', 'MODERATE (Mitigated)'), ('HIGH (Mitigated)', 'HIGH (Mitigated)'), ('LOW-MODERATE', 'LOW-MODERATE'), ('MODERATE-HIGH', 'MODERATE-HIGH'), ('LOW(High Near Rivers)', 'LOW(High Near Rivers)'), ('LOW(H/M Near Rivers)', 'LOW(H/M Near Rivers)'), ('MODERATE(High Near Rivers)', 'MODERATE(High Near Rivers)'), ('LOW(High On Slopes)', 'LOW(High On Slopes)'), ('MODERATE(High On Slopes)', 'MODERATE(High On Slopes)'), ('LOW(H/M On Slopes)', 'LOW(H/M On Slopes)'), ('LOW(High Near Creeks)', 'LOW(High Near Creeks)'), ('LOW(Moderate Near Creeks)', 'LOW(Moderate Near Creeks)'), ('MODERATE(High Near Creeks)', 'MODERATE(High Near Creeks)'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=100, verbose_name='Landslide Rating'),
        ),
        migrations.AlterField(
            model_name='history',
            name='barangay_img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='history_imgs', verbose_name='Image'),
        ),
    ]
