# Generated by Django 3.2.7 on 2022-07-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0008_auto_20220702_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['id'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
        migrations.AddField(
            model_name='announcements',
            name='announ_image',
            field=models.ImageField(blank=True, null=True, upload_to='announ_images', verbose_name='Image (Optional)'),
        ),
        migrations.CreateModel(
            name='Hotlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(blank=True, help_text='TeleComm Companies (i.e., Smart, Globe) Channel Type (i.e., Radio Frequencies,Landline,Department)', max_length=20, null=True, verbose_name='Channel - Medium Type')),
                ('contact_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='Number')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliary.contacts')),
            ],
            options={
                'verbose_name': 'Hotline',
                'verbose_name_plural': 'Hotlines',
                'ordering': ['-contacts'],
            },
        ),
    ]
