# Generated by Django 3.2.7 on 2022-07-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0009_auto_20220711_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evac_Centers',
        ),
        migrations.DeleteModel(
            name='Warning_Devices',
        ),
        migrations.DeleteModel(
            name='Warning_Signs',
        ),
    ]
