# Generated by Django 3.2.7 on 2022-07-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0002_auto_20220701_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flood_guidelines',
            options={'ordering': ['guide_id'], 'verbose_name': "'Flood Guidelines'", 'verbose_name_plural': 'Flood Guidelines'},
        ),
        migrations.AlterModelOptions(
            name='flood_procedures',
            options={'ordering': ['procedure_id'], 'verbose_name': 'Flood Procedure', 'verbose_name_plural': 'Flood Procedures'},
        ),
    ]
