# Generated by Django 3.2.7 on 2022-05-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evac_Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
                ('building_img', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='evac_center_imgs')),
            ],
            options={
                'verbose_name': 'Evacuation Center',
                'verbose_name_plural': 'Evacuation Centers',
            },
        ),
        migrations.CreateModel(
            name='Warning_Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
                ('device_info', models.TextField()),
                ('device_img', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='device_imgs')),
            ],
            options={
                'verbose_name': 'Early Warning Device',
                'verbose_name_plural': 'Early Warning Devices',
            },
        ),
        migrations.CreateModel(
            name='Warning_Signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
                ('sign_img', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='sign_imgs')),
            ],
            options={
                'verbose_name': 'Warning Sign',
                'verbose_name_plural': 'Warning Signs',
            },
        ),
    ]
