# Generated by Django 3.2.7 on 2022-05-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0002_disaster_assessment_disaster_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaster_history',
            name='purok_assessments',
        ),
    ]
