# Generated by Django 3.2.7 on 2022-05-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0004_disaster_assessment_barangay_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disaster_Assessment',
        ),
        migrations.AddField(
            model_name='disaster_history',
            name='barangay_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
