# Generated by Django 3.2.7 on 2022-05-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0005_auto_20220528_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disaster_history',
            options={'ordering': ['barangay_name'], 'verbose_name': 'Disaster History', 'verbose_name_plural': 'Disaster Histories'},
        ),
    ]
