# Generated by Django 3.2.7 on 2022-05-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0006_alter_disaster_history_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geohazard_img', models.ImageField(blank=True, upload_to='history_imgs')),
                ('geohazard_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(choices=[('Alegria', 'Alegria'), ('Bagacay', 'Bagacay'), ('Baluntay', 'Baluntay'), ('Datal Anggas', 'Datal Anggas'), ('Domolok', 'Domolok'), ('Kawas', 'Kawas'), ('Ladol', 'Ladol'), ('Maribulan', 'Maribulan'), ('Pag-Asa', 'Pag-Asa'), ('Paraiso', 'Paraiso'), ('Poblacion', 'Poblacion'), ('Spring', 'Spring'), ('Tokawal', 'Tokawal')], default='Alegria', max_length=100)),
                ('barangay_img', models.ImageField(blank=True, upload_to='history_imgs')),
                ('barangay_info', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Disaster_History',
        ),
        migrations.AddField(
            model_name='geohazard',
            name='barangay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geohazards', to='auxiliary.history'),
        ),
    ]
