# Generated by Django 3.2.7 on 2022-05-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliary', '0007_auto_20220529_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geohazard',
            old_name='barangay',
            new_name='history',
        ),
    ]
