# Generated by Django 3.2.7 on 2022-04-24 10:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flood',
            fields=[
                ('flood_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('suscep_level', models.CharField(max_length=50, unique=True)),
                ('suscep_info', models.TextField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flood_Guidelines',
            fields=[
                ('guide_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_level', models.CharField(max_length=50, unique=True)),
                ('alert_level_guide', models.TextField()),
                ('date_published', models.DateField(default=datetime.date.today)),
                ('flood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flood.flood')),
            ],
            options={
                'verbose_name': "'Flood Guidelines'",
                'verbose_name_plural': 'Flood Guidelines',
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='Flood_Evac_Procedures',
            fields=[
                ('evac_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('procedure_name', models.CharField(max_length=50, unique=True)),
                ('procedure_content', models.TextField()),
                ('flood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flood.flood')),
            ],
            options={
                'verbose_name': 'Evacuation Procedure',
                'verbose_name_plural': 'Flood Evacuation Procedures',
            },
        ),
        migrations.CreateModel(
            name='Flood_Dropdown',
            fields=[
                ('flood_drop_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('barangay_name', models.CharField(choices=[('Alegria', 'Alegria'), ('Bagacay', 'Bagacay'), ('Baluntay', 'Baluntay'), ('Datal Anggas', 'Datal Anggas'), ('Domolok', 'Domolok'), ('Kawas', 'Kawas'), ('Ladol', 'Ladol'), ('Maribulan', 'Maribulan'), ('Pag-Asa', 'Pag-Asa'), ('Paraiso', 'Paraiso'), ('Poblacion', 'Poblacion'), ('Spring', 'Spring'), ('Tokawal', 'Tokawal')], default='Alegria', max_length=50, unique=True)),
                ('latitude', models.FloatField(blank=True, default=None)),
                ('longitude', models.FloatField(blank=True, default=None)),
                ('map_marker_img', models.ImageField(blank=True, default='default.jpg', upload_to='flood_marker_imgs')),
                ('map_marker_info', models.TextField()),
                ('barangay_suscep_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangay_level', to='flood.flood')),
                ('flood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flood.flood')),
            ],
            options={
                'verbose_name': "'Barangay'",
                'verbose_name_plural': 'Flood Dropdown',
                'ordering': ['barangay_name'],
            },
        ),
    ]
