# Generated by Django 3.2.7 on 2022-04-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0002_remove_flood_dropdown_flood_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flood_dropdown',
            name='barangay_suscep_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flood.flood'),
        ),
    ]
