# Generated by Django 3.2.7 on 2022-04-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0005_alter_flood_dropdown_barangay_suscep_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flood_dropdown',
            name='barangay_suscep_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], max_length=50),
        ),
    ]
