# Generated by Django 3.2.7 on 2022-04-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0006_alter_flood_dropdown_barangay_suscep_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flood_dropdown',
            name='map_marker_img',
            field=models.ImageField(default='default.jpg', upload_to='flood_marker_imgs'),
        ),
    ]
