# Generated by Django 3.2.7 on 2022-04-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0007_alter_flood_dropdown_map_marker_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flood_dropdown',
            name='map_marker_img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='flood_marker_imgs'),
        ),
    ]
