# Generated by Django 3.2.7 on 2022-05-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0008_alter_flood_dropdown_map_marker_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flood_Guidelines',
        ),
    ]
