# Generated by Django 3.2.7 on 2022-05-16 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0009_delete_flood_guidelines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flood_Guidelines',
            fields=[
                ('guide_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_level', models.CharField(max_length=50, unique=True)),
                ('alert_level_guide', models.TextField()),
                ('date_published', models.DateField(default=datetime.date.today)),
                ('flood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flood.flood')),
            ],
            options={
                'verbose_name': "'Flood Guidelines'",
                'verbose_name_plural': 'Flood Guidelines',
                'ordering': ['-date_published'],
            },
        ),
    ]
