# Generated by Django 3.2.7 on 2022-05-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0010_flood_guidelines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flood_Guidelines',
            new_name='Guidelines',
        ),
    ]
