# Generated by Django 3.2.7 on 2022-05-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0011_rename_flood_guidelines_guidelines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guidelines',
            new_name='Flood_Guidelines',
        ),
    ]
