# Generated by Django 3.2.7 on 2022-06-30 17:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landslide',
            fields=[
                ('lands_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('suscep_level', models.CharField(choices=[('N/A', 'N/A'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3')], default='N/A', max_length=50, unique=True, verbose_name='Response Level')),
                ('suscep_info', models.TextField(verbose_name='Response Level Description')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Landslide_Markers',
            fields=[
                ('lands_marker_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('barangay_name', models.CharField(choices=[('Alegria', 'Alegria'), ('Bagacay', 'Bagacay'), ('Baluntay', 'Baluntay'), ('Datal Anggas', 'Datal Anggas'), ('Domolok', 'Domolok'), ('Kawas', 'Kawas'), ('Ladol', 'Ladol'), ('Maribulan', 'Maribulan'), ('Pag-Asa', 'Pag-Asa'), ('Paraiso', 'Paraiso'), ('Poblacion', 'Poblacion'), ('Spring', 'Spring'), ('Tokawal', 'Tokawal')], default='Alegria', max_length=50, unique=True)),
                ('barangay_suscep_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('map_marker_img', models.ImageField(blank=True, default='default.jpg', upload_to='landslide_marker_imgs')),
                ('map_marker_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Landslide Dropdown',
                'verbose_name_plural': 'Landslide Dropdown',
                'ordering': ['barangay_name'],
            },
        ),
        migrations.CreateModel(
            name='Landslide_Procedures',
            fields=[
                ('procedure_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('procedure_name', models.CharField(max_length=50, unique=True)),
                ('procedure_content', models.TextField()),
                ('landslide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landslide.landslide')),
            ],
            options={
                'verbose_name': 'Evacuation Procedure',
                'verbose_name_plural': 'Landslide Evacuation Procedures',
            },
        ),
        migrations.CreateModel(
            name='Landslide_Guidelines',
            fields=[
                ('guide_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_level', models.CharField(max_length=50, unique=True)),
                ('alert_level_guide', models.TextField()),
                ('date_published', models.DateField(default=datetime.date.today)),
                ('landslide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landslide.landslide')),
            ],
            options={
                'verbose_name': 'Landslide Guidelines',
                'verbose_name_plural': 'Landslide Guidelines',
                'ordering': ['-date_published'],
            },
        ),
    ]
