# Generated by Django 3.2.7 on 2022-07-01 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landslide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landslide_markers',
            options={'ordering': ['barangay_name'], 'verbose_name': 'Landslide Marker', 'verbose_name_plural': 'Landslide Markers'},
        ),
        migrations.AlterModelOptions(
            name='landslide_procedures',
            options={'verbose_name': 'Landslide Procedure', 'verbose_name_plural': 'Landslide Procedures'},
        ),
        migrations.AlterField(
            model_name='landslide',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='landslide_guidelines',
            name='alert_level',
            field=models.CharField(max_length=50, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='landslide_guidelines',
            name='alert_level_guide',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='landslide_guidelines',
            name='landslide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landslide.landslide', verbose_name='Response Levels'),
        ),
        migrations.AlterField(
            model_name='landslide_markers',
            name='barangay_suscep_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], max_length=50, verbose_name='Risk Level'),
        ),
        migrations.AlterField(
            model_name='landslide_procedures',
            name='landslide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landslide.landslide', verbose_name='Response Levels'),
        ),
    ]
