# Generated by Django 3.2.7 on 2022-07-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landslide', '0002_auto_20220701_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landslide_guidelines',
            options={'ordering': ['guide_id'], 'verbose_name': 'Landslide Guidelines', 'verbose_name_plural': 'Landslide Guidelines'},
        ),
    ]
