# Generated by Django 3.2.7 on 2022-07-18 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide', '0004_landslide_choropleth'),
    ]

    operations = [
        migrations.AddField(
            model_name='landslide_choropleth',
            name='date_changed',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
