# Generated by Django 3.2.7 on 2022-07-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evac_Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50, unique=True, verbose_name='Building Name')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('building_img', models.ImageField(default='default.jpg', upload_to='evac_center_imgs', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Evacuation Center',
                'verbose_name_plural': 'Evacuation Centers',
            },
        ),
        migrations.CreateModel(
            name='Warning_Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50, unique=True, verbose_name='Device Name')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('device_info', models.TextField(verbose_name='Description')),
                ('device_img', models.ImageField(default='default.jpg', upload_to='device_imgs', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Warning Device',
                'verbose_name_plural': 'Warning Devices',
            },
        ),
        migrations.CreateModel(
            name='Warning_Signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=50, unique=True, verbose_name='Sign Name')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sign_img', models.ImageField(default='default.jpg', upload_to='sign_imgs', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Warning Sign',
                'verbose_name_plural': 'Warning Signs',
            },
        ),
    ]
