# Generated by Django 3.2.7 on 2022-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_auxiliary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evac_centers',
            name='location',
            field=models.CharField(help_text='Places/Sites (i.e., Street Name,Purok,Barangay,Land Marks)', max_length=50),
        ),
        migrations.AlterField(
            model_name='warning_devices',
            name='location',
            field=models.CharField(help_text='Places/Sites (i.e., Street Name,Purok,Barangay,Land Marks)', max_length=50),
        ),
        migrations.AlterField(
            model_name='warning_signs',
            name='location',
            field=models.CharField(help_text='Places/Sites (i.e., Street Name,Purok,Barangay,Land Marks)', max_length=50),
        ),
    ]
